name: Deploy Front to Heroku PROD
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present  --configuration=production
    # Lint
    - name: eslint
      uses: icrawl/action-eslint@v1
    # Test
    - name : test
      run: npm run test
    # Deploy
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.5.6 
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKUPROD_API_APP}}
        heroku_email: ${{secrets.HEROKU_API_EMAIL}}
    # Send mail
    - name: Send some mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: CI/CD job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        to: angsymftest@gmail.com, ${{github.event.pusher.email}}
        from: Luke Skywalker # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html